server:
  port: 8003
  forward-headers-strategy: framework

spring:
  application:
    name: koala-cloud-service-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
      config:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
  config:
    import:
      - nacos:koala-cloud-service-demo.yml?refresh=true
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha