server:
  port: 8003

spring:
  application:
    name: koala-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
      config:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
  config:
    import:
      - nacos:koala-cloud-consumer.yml?refresh=true