server:
  port: 8000
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.r2dbc: debug
    cn.koala.cloud.gateway: debug

spring:
  application:
    name: koala-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
      config:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
  config:
    import:
      - nacos:koala-cloud-gateway.yml?refresh=true
  jackson:
    default-property-inclusion: non_empty
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/koala_cloud_demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: koala
    password: Koala@2023
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.100.77:8001

koala:
  cloud:
    gateway:
      dynamic-routing: true

springdoc:
  swagger-ui:
    config-url: /gateway/swagger-config
    tags-sorter: alpha
    use-root-path: true