server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/koala_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: koala
    password: koala
  application:
    name: koala-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
      config:
        server-addr: 127.0.0.1:8848
        namespace: koala-cloud
  config:
    import:
      - nacos:koala-cloud-gateway.yml?refresh=true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8001